import { INodeProperties } from 'n8n-workflow';

const IGNORED_CREATE = new Set([
	'customerCategoryName',
	'sectorName',
	'ratingName',
	'leadSourceName',
	'leadRatingName',
]);

const IGNORED_UPDATE = new Set([
	'customerCategoryName',
	'sectorName',
	'ratingName',
	'leadSourceName',
	'leadRatingName',
	'shipmentMethodName',
	'customerShipmentMethodName',
]);

// All scalar/primitive Party fields from the Weclapp API.
// Nested array-of-object fields (addresses, bankAccounts, etc.) are excluded.
const ALL_PARTY_OPTIONS: INodeProperties[] = [
	{ displayName: 'Allow Purchase Order Creation', name: 'allowPurchaseOrderCreation', type: 'boolean', default: false },
	{
		displayName: 'Birth Date', name: 'birthDate', type: 'number', default: 0,
		description: 'Unix timestamp in milliseconds',
	},
	{
		displayName: 'Commercial Language',
		name: 'commercialLanguageId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCommercialLanguages' },
		default: '',
	},
	{ displayName: 'Company', name: 'company', type: 'string', default: '' },
	{ displayName: 'Company 2', name: 'company2', type: 'string', default: '' },
	{ displayName: 'Company Size ID', name: 'companySizeId', type: 'string', default: '' },
	{ displayName: 'Company Size Name', name: 'companySizeName', type: 'string', default: '' },
	{ displayName: 'Competitor', name: 'competitor', type: 'boolean', default: false },
	{
		displayName: 'Currency',
		name: 'currencyId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCurrencies' },
		default: '',
	},
	{ displayName: 'Currency Name', name: 'currencyName', type: 'string', default: '' },
	{ displayName: 'Customer', name: 'customer', type: 'boolean', default: false },
	{ displayName: 'Customer Amount Insured', name: 'customerAmountInsured', type: 'number', default: 0 },
	{ displayName: 'Customer Annual Revenue', name: 'customerAnnualRevenue', type: 'number', default: 0 },
	{ displayName: 'Customer Block Notice', name: 'customerBlockNotice', type: 'string', default: '' },
	{ displayName: 'Customer Blocked', name: 'customerBlocked', type: 'boolean', default: false },
	{
		displayName: 'Customer Business Type', name: 'customerBusinessType', type: 'options', default: 'B2B',
		options: [
			{ name: 'B2B', value: 'B2B' },
			{ name: 'B2C', value: 'B2C' },
			{ name: 'B2G', value: 'B2G' },
		],
	},
	{
		displayName: 'Customer Category',
		name: 'customerCategoryId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCustomerCategories' },
		default: '',
	},
	{ displayName: 'Customer Category Name', name: 'customerCategoryName', type: 'string', default: '' },
	{ displayName: 'Customer Credit Limit', name: 'customerCreditLimit', type: 'number', default: 0 },
	{ displayName: 'Customer Current Sales Stage ID', name: 'customerCurrentSalesStageId', type: 'string', default: '' },
	{ displayName: 'Customer Current Sales Stage Name', name: 'customerCurrentSalesStageName', type: 'string', default: '' },
	{ displayName: 'Customer Debtor Account ID', name: 'customerDebtorAccountId', type: 'string', default: '' },
	{ displayName: 'Customer Debtor Account Number', name: 'customerDebtorAccountNumber', type: 'string', default: '' },
	{ displayName: 'Customer Debtor Accounting Code ID', name: 'customerDebtorAccountingCodeId', type: 'string', default: '' },
	{ displayName: 'Customer Default Header Discount', name: 'customerDefaultHeaderDiscount', type: 'number', default: 0 },
	{ displayName: 'Customer Default Header Surcharge', name: 'customerDefaultHeaderSurcharge', type: 'number', default: 0 },
	{
		displayName: 'Customer Default Shipping Carrier',
		name: 'customerDefaultShippingCarrierId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getShippingCarriers' },
		default: '',
	},
	{ displayName: 'Customer Delivery Block', name: 'customerDeliveryBlock', type: 'boolean', default: false },
	{ displayName: 'Customer Insolvent', name: 'customerInsolvent', type: 'boolean', default: false },
	{ displayName: 'Customer Insured', name: 'customerInsured', type: 'boolean', default: false },
	{ displayName: 'Customer Internal Note', name: 'customerInternalNote', type: 'string', default: '' },
	{ displayName: 'Customer Loss Description', name: 'customerLossDescription', type: 'string', default: '', description: 'Maximum 255 characters' },
	{ displayName: 'Customer Loss Reason ID', name: 'customerLossReasonId', type: 'string', default: '' },
	{ displayName: 'Customer Loss Reason Name', name: 'customerLossReasonName', type: 'string', default: '' },
	{ displayName: 'Customer Non-Standard Tax ID', name: 'customerNonStandardTaxId', type: 'string', default: '' },
	{ displayName: 'Customer Number', name: 'customerNumber', type: 'string', default: '' },
	{ displayName: 'Customer Number (Old)', name: 'customerNumberOld', type: 'string', default: '' },
	{
		displayName: 'Customer Payment Method',
		name: 'customerPaymentMethodId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPaymentMethods' },
		default: '',
	},
	{ displayName: 'Customer Payment Method Name', name: 'customerPaymentMethodName', type: 'string', default: '' },
	{
		displayName: 'Customer Sales Channel',
		name: 'customerSalesChannel',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getSalesChannels' },
		default: '',
	},
	{ displayName: 'Customer Sales Order Payment Type', name: 'customerSalesOrderPaymentType', type: 'string', default: '' },
	{ displayName: 'Customer Sales Probability', name: 'customerSalesProbability', type: 'number', default: 0 },
	{ displayName: 'Customer Satisfaction', name: 'customerSatisfaction', type: 'string', default: '' },
	{
		displayName: 'Customer Shipment Method',
		name: 'customerShipmentMethodId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getShipmentMethods' },
		default: '',
	},
	{ displayName: 'Customer Shipment Method Name', name: 'customerShipmentMethodName', type: 'string', default: '' },
	{ displayName: 'Customer Supplier Number', name: 'customerSupplierNumber', type: 'string', default: '' },
	{
		displayName: 'Customer Term of Payment',
		name: 'customerTermOfPaymentId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTermsOfPayment' },
		default: '',
	},
	{ displayName: 'Customer Term of Payment Name', name: 'customerTermOfPaymentName', type: 'string', default: '' },
	{ displayName: 'Customer Use Customs Tariff Number', name: 'customerUseCustomsTariffNumber', type: 'boolean', default: false },
	{ displayName: 'Delivery Address ID', name: 'deliveryAddressId', type: 'string', default: '' },
	{ displayName: 'Delivery Email Addresses ID', name: 'deliveryEmailAddressesId', type: 'string', default: '' },
	{
		displayName: 'Description', name: 'description', type: 'string', default: '',
		typeOptions: { rows: 3 },
	},
	{ displayName: 'Dunning Address ID', name: 'dunningAddressId', type: 'string', default: '' },
	{ displayName: 'Dunning Email Addresses ID', name: 'dunningEmailAddressesId', type: 'string', default: '' },
	{ displayName: 'Enable Dropshipping in New Supply Sources', name: 'enableDropshippingInNewSupplySources', type: 'boolean', default: false },
	{ displayName: 'EORI Number', name: 'eoriNumber', type: 'string', default: '' },
	{ displayName: 'Factoring', name: 'factoring', type: 'boolean', default: false },
	{ displayName: 'Fax', name: 'fax', type: 'string', default: '' },
	{ displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
	{ displayName: 'Fix Phone 2', name: 'fixPhone2', type: 'string', default: '' },
	{ displayName: 'Fixed Responsible User', name: 'fixedResponsibleUser', type: 'boolean', default: false },
	{ displayName: 'Former Sales Partner', name: 'formerSalesPartner', type: 'boolean', default: false },
	{ displayName: 'Habitual Exporter', name: 'habitualExporter', type: 'boolean', default: false },
	{ displayName: 'Image ID', name: 'imageId', type: 'string', default: '' },
	{ displayName: 'Invoice Address ID', name: 'invoiceAddressId', type: 'string', default: '' },
	{ displayName: 'Invoice Block', name: 'invoiceBlock', type: 'boolean', default: false },
	{ displayName: 'Invoice Recipient ID', name: 'invoiceRecipientId', type: 'string', default: '' },
	{ displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
	{
		displayName: 'Lead Rating',
		name: 'leadRatingId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getLeadRatings' },
		default: '',
	},
	{ displayName: 'Lead Rating Name', name: 'leadRatingName', type: 'string', default: '' },
	{
		displayName: 'Lead Source',
		name: 'leadSourceId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getLeadSources' },
		default: '',
	},
	{ displayName: 'Lead Source Name', name: 'leadSourceName', type: 'string', default: '' },
	{
		displayName: 'Lead Status', name: 'leadStatus', type: 'options', default: 'NEW',
		options: [
			{ name: 'Converted', value: 'CONVERTED' },
			{ name: 'Disqualified', value: 'DISQUALIFIED' },
			{ name: 'New', value: 'NEW' },
			{ name: 'Prequalified', value: 'PREQUALIFIED' },
			{ name: 'Qualified', value: 'QUALIFIED' },
		],
	},
	{ displayName: 'Legal Form ID', name: 'legalFormId', type: 'string', default: '' },
	{ displayName: 'Legal Form Name', name: 'legalFormName', type: 'string', default: '' },
	{ displayName: 'Middle Name', name: 'middleName', type: 'string', default: '' },
	{ displayName: 'Mobile Phone 1', name: 'mobilePhone1', type: 'string', default: '' },
	{ displayName: 'Mobile Phone 2', name: 'mobilePhone2', type: 'string', default: '' },
	{ displayName: 'Opt-In Email', name: 'optInEmail', type: 'boolean', default: false },
	{ displayName: 'Opt-In Letter', name: 'optInLetter', type: 'boolean', default: false },
	{ displayName: 'Opt-In Phone', name: 'optInPhone', type: 'boolean', default: false },
	{ displayName: 'Opt-In SMS', name: 'optInSms', type: 'boolean', default: false },
	{ displayName: 'Parent Party ID', name: 'parentPartyId', type: 'string', default: '' },
	{
		displayName: 'Party Type', name: 'partyType', type: 'options', default: 'ORGANIZATION',
		options: [
			{ name: 'Organisation', value: 'ORGANIZATION' },
			{ name: 'Person', value: 'PERSON' },
		],
	},
	{ displayName: 'Person Company', name: 'personCompany', type: 'string', default: '' },
	{
		displayName: 'Person Department',
		name: 'personDepartmentId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPersonDepartments' },
		default: '',
	},
	{
		displayName: 'Person Role',
		name: 'personRoleId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPersonRoles' },
		default: '',
	},
	{ displayName: 'Phone', name: 'phone', type: 'string', default: '' },
	{ displayName: 'Phone Home', name: 'phoneHome', type: 'string', default: '' },
	{ displayName: 'Primary Address ID', name: 'primaryAddressId', type: 'string', default: '' },
	{ displayName: 'Primary Contact ID', name: 'primaryContactId', type: 'string', default: '' },
	{ displayName: 'Purchase Email Addresses ID', name: 'purchaseEmailAddressesId', type: 'string', default: '' },
	{ displayName: 'Purchase Via Plafond', name: 'purchaseViaPlafond', type: 'boolean', default: false },
	{
		displayName: 'Rating',
		name: 'ratingId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPartyRatings' },
		default: '',
	},
	{ displayName: 'Rating Name', name: 'ratingName', type: 'string', default: '' },
	{ displayName: 'Reference Number', name: 'referenceNumber', type: 'string', default: '' },
	{ displayName: 'Responsible User ID', name: 'responsibleUserId', type: 'string', default: '' },
	{ displayName: 'Responsible Username', name: 'responsibleUserUsername', type: 'string', default: '' },
	{ displayName: 'Sales Invoice Email Addresses ID', name: 'salesInvoiceEmailAddressesId', type: 'string', default: '' },
	{ displayName: 'Sales Order Email Addresses ID', name: 'salesOrderEmailAddressesId', type: 'string', default: '' },
	{ displayName: 'Sales Partner', name: 'salesPartner', type: 'boolean', default: false },
	{ displayName: 'Sales Partner Default Commission Fix', name: 'salesPartnerDefaultCommissionFix', type: 'number', default: 0 },
	{ displayName: 'Sales Partner Default Commission Percentage', name: 'salesPartnerDefaultCommissionPercentage', type: 'number', default: 0 },
	{
		displayName: 'Sales Partner Default Commission Type', name: 'salesPartnerDefaultCommissionType', type: 'options', default: 'NO_COMMISSION',
		options: [
			{ name: 'Fix', value: 'FIX' },
			{ name: 'Fix and Margin', value: 'FIX_AND_MARGIN' },
			{ name: 'Fix and Revenue', value: 'FIX_AND_REVENUE' },
			{ name: 'Margin', value: 'MARGIN' },
			{ name: 'No Commission', value: 'NO_COMMISSION' },
			{ name: 'Revenue', value: 'REVENUE' },
		],
	},
	{
		displayName: 'Salutation', name: 'salutation', type: 'options', default: 'NO_SALUTATION',
		options: [
			{ name: 'Company', value: 'COMPANY' },
			{ name: 'Family', value: 'FAMILY' },
			{ name: 'Mr', value: 'MR' },
			{ name: 'Mrs', value: 'MRS' },
			{ name: 'No Salutation', value: 'NO_SALUTATION' },
		],
	},
	{
		displayName: 'Sector',
		name: 'sectorId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getSectors' },
		default: '',
	},
	{ displayName: 'Sector Name', name: 'sectorName', type: 'string', default: '' },
	{ displayName: 'Supplier', name: 'supplier', type: 'boolean', default: false },
	{ displayName: 'Supplier Creditor Account ID', name: 'supplierCreditorAccountId', type: 'string', default: '' },
	{ displayName: 'Supplier Creditor Account Number', name: 'supplierCreditorAccountNumber', type: 'string', default: '' },
	{ displayName: 'Supplier Creditor Accounting Code ID', name: 'supplierCreditorAccountingCodeId', type: 'string', default: '' },
	{ displayName: 'Supplier Customer Number at Supplier', name: 'supplierCustomerNumberAtSupplier', type: 'string', default: '', description: 'Maximum 64 characters' },
	{
		displayName: 'Supplier Default Shipping Carrier',
		name: 'supplierDefaultShippingCarrierId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getShippingCarriers' },
		default: '',
	},
	{ displayName: 'Supplier Internal Note', name: 'supplierInternalNote', type: 'string', default: '' },
	{ displayName: 'Supplier Minimum Purchase Order Amount', name: 'supplierMinimumPurchaseOrderAmount', type: 'number', default: 0 },
	{ displayName: 'Supplier Non-Standard Tax ID', name: 'supplierNonStandardTaxId', type: 'string', default: '' },
	{ displayName: 'Supplier Number', name: 'supplierNumber', type: 'string', default: '' },
	{ displayName: 'Supplier Number (Old)', name: 'supplierNumberOld', type: 'string', default: '' },
	{ displayName: 'Supplier Order Block', name: 'supplierOrderBlock', type: 'boolean', default: false },
	{
		displayName: 'Supplier Payment Method',
		name: 'supplierPaymentMethodId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPaymentMethods' },
		default: '',
	},
	{ displayName: 'Supplier Payment Method Name', name: 'supplierPaymentMethodName', type: 'string', default: '' },
	{
		displayName: 'Supplier Shipment Method',
		name: 'supplierShipmentMethodId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getShipmentMethods' },
		default: '',
	},
	{ displayName: 'Supplier Shipment Method Name', name: 'supplierShipmentMethodName', type: 'string', default: '' },
	{
		displayName: 'Supplier Term of Payment',
		name: 'supplierTermOfPaymentId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTermsOfPayment' },
		default: '',
	},
	{ displayName: 'Supplier Term of Payment Name', name: 'supplierTermOfPaymentName', type: 'string', default: '' },
	{
		displayName: 'Tax',
		name: 'taxId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTaxes' },
		default: '',
	},
	{ displayName: 'Title', name: 'title', type: 'string', default: '' },
	{ displayName: 'Title ID', name: 'titleId', type: 'string', default: '' },
	{ displayName: 'VAT Identification Number', name: 'vatIdentificationNumber', type: 'string', default: '' },
	{
		displayName: 'Version', name: 'version', type: 'string', default: '',
		description: 'Entity version for optimistic locking. Send the version received from a prior GET to prevent overwriting concurrent changes.',
	},
	{ displayName: 'Website', name: 'website', type: 'string', default: '' },
	{ displayName: 'X-Rechnung Leitweg ID', name: 'xRechnungLeitwegId', type: 'string', default: '', description: 'Maximum 46 characters' },
];

function buildOptions(ignored: Set<string>): INodeProperties[] {
	return ALL_PARTY_OPTIONS.filter(opt => !ignored.has(opt.name as string));
}

const customAttributesField: INodeProperties = {
	displayName: 'Custom Attributes',
	name: 'customAttributes',
	type: 'resourceMapper',
	default: { mappingMode: 'defineBelow', value: null },
	noDataExpression: true,
	displayOptions: {
		show: {
			resource: ['party'],
			operation: ['create', 'update'],
		},
	},
	typeOptions: {
		resourceMapper: {
			resourceMapperMethod: 'getCustomAttributesForParty',
			mode: 'add',
			fieldWords: { singular: 'Custom Attribute', plural: 'Custom Attributes' },
			addAllFields: false,
			noFieldsError: 'No custom attributes found for the Party entity.',
		},
	},
};

export const partyCreateUpdateFields: INodeProperties[] = [
	{
		displayName: 'Fields',
		name: 'createFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['party'],
				operation: ['create'],
			},
		},
		options: buildOptions(IGNORED_CREATE),
	},
	{
		displayName: 'Fields to Update',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['party'],
				operation: ['update'],
			},
		},
		options: buildOptions(IGNORED_UPDATE),
	},
	customAttributesField,
];
